# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\CODES\Python\EbookCollection\empty_book.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog: QtWidgets.QDialog):
        dialog.setObjectName("dialog")
        dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        dialog.resize(460, 350)
        dialog.setMinimumSize(QtCore.QSize(460, 350))
        dialog.setMaximumSize(QtCore.QSize(460, 350))
        dialog.setAutoFillBackground(False)
        dialog.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.number_label = QtWidgets.QLabel(dialog)
        self.number_label.setMinimumSize(QtCore.QSize(200, 0))
        self.number_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.number_label.setObjectName("number_label")
        self.horizontalLayout.addWidget(self.number_label)
        self.number_spin_box = QtWidgets.QSpinBox(dialog)
        self.number_spin_box.setMinimumSize(QtCore.QSize(0, 30))
        self.number_spin_box.setFrame(True)
        self.number_spin_box.setMinimum(1)
        self.number_spin_box.setObjectName("number_spin_box")
        self.horizontalLayout.addWidget(self.number_spin_box)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.name_label = QtWidgets.QLabel(dialog)
        self.name_label.setMinimumSize(QtCore.QSize(200, 0))
        self.name_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.name_label.setObjectName("name_label")
        self.horizontalLayout_2.addWidget(self.name_label)
        self.name_line_edit = QtWidgets.QLineEdit(dialog)
        self.name_line_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.name_line_edit.setFrame(True)
        self.name_line_edit.setClearButtonEnabled(True)
        self.name_line_edit.setObjectName("name_line_edit")
        self.horizontalLayout_2.addWidget(self.name_line_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.authors_label = QtWidgets.QLabel(dialog)
        self.authors_label.setMinimumSize(QtCore.QSize(200, 0))
        self.authors_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.authors_label.setAutoFillBackground(False)
        self.authors_label.setObjectName("authors_label")
        self.horizontalLayout_3.addWidget(self.authors_label)
        self.authors_line_edit = QtWidgets.QLineEdit(dialog)
        self.authors_line_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.authors_line_edit.setFrame(True)
        self.authors_line_edit.setClearButtonEnabled(True)
        self.authors_line_edit.setObjectName("authors_line_edit")
        self.horizontalLayout_3.addWidget(self.authors_line_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.serie_label = QtWidgets.QLabel(dialog)
        self.serie_label.setMinimumSize(QtCore.QSize(200, 0))
        self.serie_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.serie_label.setObjectName("serie_label")
        self.horizontalLayout_4.addWidget(self.serie_label)
        self.serie_line_edit = QtWidgets.QLineEdit(dialog)
        self.serie_line_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.serie_line_edit.setFrame(True)
        self.serie_line_edit.setClearButtonEnabled(True)
        self.serie_line_edit.setObjectName("serie_line_edit")
        self.horizontalLayout_4.addWidget(self.serie_line_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.serie_volume_label = QtWidgets.QLabel(dialog)
        self.serie_volume_label.setMinimumSize(QtCore.QSize(200, 0))
        self.serie_volume_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.serie_volume_label.setObjectName("serie_volume_label")
        self.horizontalLayout_5.addWidget(self.serie_volume_label)
        self.serie_volume_spin_box = QtWidgets.QDoubleSpinBox(dialog)
        self.serie_volume_spin_box.setMinimumSize(QtCore.QSize(0, 30))
        self.serie_volume_spin_box.setMaximum(9999.99)
        self.serie_volume_spin_box.setProperty("value", 1.0)
        self.serie_volume_spin_box.setObjectName("serie_volume_spin_box")
        self.horizontalLayout_5.addWidget(self.serie_volume_spin_box)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.format_label = QtWidgets.QLabel(dialog)
        self.format_label.setMinimumSize(QtCore.QSize(200, 0))
        self.format_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.format_label.setObjectName("format_label")
        self.horizontalLayout_6.addWidget(self.format_label)
        self.format_combobox = QtWidgets.QComboBox(dialog)
        self.format_combobox.setMinimumSize(QtCore.QSize(0, 30))
        self.format_combobox.setObjectName("format_combobox")
        self.horizontalLayout_6.addWidget(self.format_combobox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.button_box = QtWidgets.QDialogButtonBox(dialog)
        self.button_box.setMinimumSize(QtCore.QSize(0, 40))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(dialog)
        self.button_box.accepted.connect(dialog.accept)
        self.button_box.rejected.connect(dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog: QtWidgets.QDialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Dialog"))
        self.number_label.setText(_translate("dialog", "TextLabel"))
        self.name_label.setText(_translate("dialog", "TextLabel"))
        self.authors_label.setText(_translate("dialog", "TextLabelj"))
        self.serie_label.setText(_translate("dialog", "TextLabel"))
        self.serie_volume_label.setText(_translate("dialog", "TextLabel"))
        self.format_label.setText(_translate("dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())
