# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\CODES\Python\EbookCollection\home.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_home_window(QtWidgets.QMainWindow):
    def setupUi(self, home_window: QtWidgets.QMainWindow):
        home_window.setObjectName("home_window")
        home_window.resize(1024, 700)
        home_window.setMinimumSize(QtCore.QSize(1024, 700))
        home_window.setMaximumSize(QtCore.QSize(16777215, 16777215))
        home_window.setAutoFillBackground(True)
        home_window.setDocumentMode(False)
        home_window.setDockNestingEnabled(False)
        home_window.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        home_window.setUnifiedTitleAndToolBarOnMac(False)
        self.widget = QtWidgets.QWidget(home_window)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.central_block = QtWidgets.QVBoxLayout()
        self.central_block.setObjectName("central_block")
        self.central_block_table = QtWidgets.QTableWidget(self.widget)
        self.central_block_table.setMinimumSize(QtCore.QSize(500, 0))
        self.central_block_table.setAutoFillBackground(False)
        self.central_block_table.setStyleSheet("")
        self.central_block_table.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.central_block_table.setProperty("showDropIndicator", False)
        self.central_block_table.setDragDropOverwriteMode(False)
        self.central_block_table.setAlternatingRowColors(True)
        self.central_block_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.central_block_table.setTextElideMode(QtCore.Qt.ElideRight)
        self.central_block_table.setShowGrid(True)
        self.central_block_table.setCornerButtonEnabled(False)
        self.central_block_table.setObjectName("central_block_table")
        self.central_block_table.setColumnCount(5)
        self.central_block_table.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.central_block_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.central_block_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.central_block_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.central_block_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.central_block_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.central_block_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.central_block_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsEnabled)
        self.central_block_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.central_block_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.central_block_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.central_block_table.setItem(1, 1, item)
        self.central_block_table.horizontalHeader().setVisible(True)
        self.central_block_table.horizontalHeader().setCascadingSectionResizes(True)
        self.central_block_table.horizontalHeader().setHighlightSections(False)
        self.central_block_table.horizontalHeader().setMinimumSectionSize(100)
        self.central_block_table.horizontalHeader().setSortIndicatorShown(True)
        self.central_block_table.horizontalHeader().setStretchLastSection(False)
        self.central_block_table.verticalHeader().setVisible(False)
        self.central_block_table.verticalHeader().setCascadingSectionResizes(True)
        self.central_block_table.verticalHeader().setHighlightSections(False)
        self.central_block_table.verticalHeader().setMinimumSectionSize(0)
        self.central_block_table.verticalHeader().setSortIndicatorShown(False)
        self.central_block_table.verticalHeader().setStretchLastSection(False)
        self.central_block.addWidget(self.central_block_table)
        self.horizontalLayout_5.addLayout(self.central_block)
        home_window.setCentralWidget(self.widget)
        self.header_block = QtWidgets.QDockWidget(home_window)
        self.header_block.setMinimumSize(QtCore.QSize(322, 95))
        self.header_block.setMaximumSize(QtCore.QSize(524287, 95))
        self.header_block.setAutoFillBackground(False)
        self.header_block.setFeatures(QtWidgets.QDockWidget.DockWidgetMovable)
        self.header_block.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.header_block.setObjectName("header_block")
        self.header_block_contents = QtWidgets.QWidget()
        self.header_block_contents.setMinimumSize(QtCore.QSize(0, 0))
        self.header_block_contents.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.header_block_contents.setObjectName("header_block_contents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.header_block_contents)
        self.horizontalLayout_4.setContentsMargins(9, 4, 9, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.header_block_contents2 = QtWidgets.QWidget(self.header_block_contents)
        self.header_block_contents2.setObjectName("header_block_contents2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header_block_contents2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.header_block_btn_add_book = QtWidgets.QPushButton(self.header_block_contents2)
        self.header_block_btn_add_book.setMinimumSize(QtCore.QSize(70, 70))
        self.header_block_btn_add_book.setMaximumSize(QtCore.QSize(70, 70))
        self.header_block_btn_add_book.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.header_block_btn_add_book.setAutoFillBackground(False)
        self.header_block_btn_add_book.setStyleSheet("")
        self.header_block_btn_add_book.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ressources/icons/white/book_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.header_block_btn_add_book.setIcon(icon)
        self.header_block_btn_add_book.setIconSize(QtCore.QSize(60, 60))
        self.header_block_btn_add_book.setAutoDefault(False)
        self.header_block_btn_add_book.setDefault(False)
        self.header_block_btn_add_book.setFlat(False)
        self.header_block_btn_add_book.setObjectName("header_block_btn_add_book")
        self.horizontalLayout_3.addWidget(self.header_block_btn_add_book)
        self.header_block_btn_create_book = QtWidgets.QPushButton(self.header_block_contents2)
        self.header_block_btn_create_book.setMinimumSize(QtCore.QSize(70, 70))
        self.header_block_btn_create_book.setMaximumSize(QtCore.QSize(70, 70))
        self.header_block_btn_create_book.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.header_block_btn_create_book.setAutoFillBackground(False)
        self.header_block_btn_create_book.setStyleSheet("")
        self.header_block_btn_create_book.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ressources/icons/white/book_new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.header_block_btn_create_book.setIcon(icon1)
        self.header_block_btn_create_book.setIconSize(QtCore.QSize(60, 60))
        self.header_block_btn_create_book.setAutoDefault(False)
        self.header_block_btn_create_book.setDefault(False)
        self.header_block_btn_create_book.setFlat(False)
        self.header_block_btn_create_book.setObjectName("header_block_btn_create_book")
        self.horizontalLayout_3.addWidget(self.header_block_btn_create_book)
        self.header_block_btn_del_book = QtWidgets.QPushButton(self.header_block_contents2)
        self.header_block_btn_del_book.setMinimumSize(QtCore.QSize(70, 70))
        self.header_block_btn_del_book.setMaximumSize(QtCore.QSize(70, 70))
        self.header_block_btn_del_book.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.header_block_btn_del_book.setAutoFillBackground(False)
        self.header_block_btn_del_book.setStyleSheet("")
        self.header_block_btn_del_book.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ressources/icons/white/book_del.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.header_block_btn_del_book.setIcon(icon2)
        self.header_block_btn_del_book.setIconSize(QtCore.QSize(60, 60))
        self.header_block_btn_del_book.setAutoDefault(False)
        self.header_block_btn_del_book.setDefault(False)
        self.header_block_btn_del_book.setFlat(False)
        self.header_block_btn_del_book.setObjectName("header_block_btn_del_book")
        self.horizontalLayout_3.addWidget(self.header_block_btn_del_book)
        spacerItem = QtWidgets.QSpacerItem(427, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.header_block_btn_settings = QtWidgets.QPushButton(self.header_block_contents2)
        self.header_block_btn_settings.setMinimumSize(QtCore.QSize(70, 70))
        self.header_block_btn_settings.setMaximumSize(QtCore.QSize(70, 70))
        self.header_block_btn_settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.header_block_btn_settings.setAutoFillBackground(False)
        self.header_block_btn_settings.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ressources/icons/white/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.header_block_btn_settings.setIcon(icon3)
        self.header_block_btn_settings.setIconSize(QtCore.QSize(60, 60))
        self.header_block_btn_settings.setCheckable(False)
        self.header_block_btn_settings.setFlat(False)
        self.header_block_btn_settings.setObjectName("header_block_btn_settings")
        self.horizontalLayout_3.addWidget(self.header_block_btn_settings)
        self.horizontalLayout_4.addWidget(self.header_block_contents2)
        self.header_block.setWidget(self.header_block_contents)
        home_window.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.header_block)
        self.sorting_block = DockWidget(home_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sorting_block.sizePolicy().hasHeightForWidth())
        self.sorting_block.setSizePolicy(sizePolicy)
        self.sorting_block.setMinimumSize(QtCore.QSize(230, 227))
        self.sorting_block.setMaximumSize(QtCore.QSize(600, 524287))
        self.sorting_block.setFloating(False)
        self.sorting_block.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.sorting_block.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.sorting_block.setObjectName("sorting_block")
        self.sorting_block_contents = QtWidgets.QWidget()
        self.sorting_block_contents.setMaximumSize(QtCore.QSize(600, 16777215))
        self.sorting_block_contents.setObjectName("sorting_block_contents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sorting_block_contents)
        self.verticalLayout_2.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sorting_block_search_label = QtWidgets.QLabel(self.sorting_block_contents)
        self.sorting_block_search_label.setMinimumSize(QtCore.QSize(60, 20))
        self.sorting_block_search_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.sorting_block_search_label.setObjectName("sorting_block_search_label")
        self.horizontalLayout_2.addWidget(self.sorting_block_search_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.sorting_block_search_edit = QtWidgets.QLineEdit(self.sorting_block_contents)
        self.sorting_block_search_edit.setMaximumSize(QtCore.QSize(10, 16777215))
        self.sorting_block_search_edit.setObjectName("sorting_block_search_edit")
        self.horizontalLayout_2.addWidget(self.sorting_block_search_edit)
        self.sorting_block_search_button = QtWidgets.QPushButton(self.sorting_block_contents)
        self.sorting_block_search_button.setMinimumSize(QtCore.QSize(20, 20))
        self.sorting_block_search_button.setMaximumSize(QtCore.QSize(20, 20))
        self.sorting_block_search_button.setText("")
        self.sorting_block_search_button.setObjectName("sorting_block_search_button")
        self.horizontalLayout_2.addWidget(self.sorting_block_search_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.sorting_block_search_area = QtWidgets.QGroupBox(self.sorting_block_contents)
        self.sorting_block_search_area.setStyleSheet("")
        self.sorting_block_search_area.setFlat(True)
        self.sorting_block_search_area.setObjectName("sorting_block_search_area")
        self.sorting_block_search_area_contents = QtWidgets.QVBoxLayout(self.sorting_block_search_area)
        self.sorting_block_search_area_contents.setObjectName("sorting_block_search_area_contents")
        self.verticalLayout.addWidget(self.sorting_block_search_area)
        self.sorting_block_tree = QtWidgets.QTreeWidget(self.sorting_block_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sorting_block_tree.sizePolicy().hasHeightForWidth())
        self.sorting_block_tree.setSizePolicy(sizePolicy)
        self.sorting_block_tree.setMinimumSize(QtCore.QSize(218, 100))
        self.sorting_block_tree.setMaximumSize(QtCore.QSize(600, 16777215))
        self.sorting_block_tree.setRootIsDecorated(True)
        self.sorting_block_tree.setUniformRowHeights(True)
        self.sorting_block_tree.setItemsExpandable(True)
        self.sorting_block_tree.setAllColumnsShowFocus(False)
        self.sorting_block_tree.setWordWrap(True)
        self.sorting_block_tree.setHeaderHidden(True)
        self.sorting_block_tree.setObjectName("sorting_block_tree")
        item_0 = QtWidgets.QTreeWidgetItem(self.sorting_block_tree)
        item_0 = QtWidgets.QTreeWidgetItem(self.sorting_block_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.sorting_block_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.sorting_block_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout.addWidget(self.sorting_block_tree)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.sorting_block.setWidget(self.sorting_block_contents)
        home_window.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.sorting_block)
        self.info_block = DockWidget(home_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_block.sizePolicy().hasHeightForWidth())
        self.info_block.setSizePolicy(sizePolicy)
        self.info_block.setMinimumSize(QtCore.QSize(230, 305))
        self.info_block.setMaximumSize(QtCore.QSize(600, 524287))
        self.info_block.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.info_block.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.info_block.setObjectName("info_block")
        self.info_block_contents = QtWidgets.QWidget()
        self.info_block_contents.setObjectName("info_block_contents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.info_block_contents)
        self.verticalLayout_4.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.info_block_cover = QtWidgets.QPushButton(self.info_block_contents)
        self.info_block_cover.setMinimumSize(QtCore.QSize(190, 160))
        self.info_block_cover.setMaximumSize(QtCore.QSize(190, 160))
        self.info_block_cover.setFocusPolicy(QtCore.Qt.NoFocus)
        self.info_block_cover.setStyleSheet("background: transparent !important;")
        self.info_block_cover.setText("")
        self.info_block_cover.setIconSize(QtCore.QSize(160, 160))
        self.info_block_cover.setObjectName("info_block_cover")
        self.horizontalLayout.addWidget(self.info_block_cover)
        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.info_block_title = QtWidgets.QHBoxLayout()
        self.info_block_title.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.info_block_title.setSpacing(0)
        self.info_block_title.setObjectName("info_block_title")
        self.info_block_title_label = QtWidgets.QLabel(self.info_block_contents)
        self.info_block_title_label.setMinimumSize(QtCore.QSize(70, 20))
        self.info_block_title_label.setMaximumSize(QtCore.QSize(70, 20))
        self.info_block_title_label.setObjectName("info_block_title_label")
        self.info_block_title.addWidget(self.info_block_title_label)
        self.info_block_title_value = QtWidgets.QLabel(self.info_block_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_block_title_value.sizePolicy().hasHeightForWidth())
        self.info_block_title_value.setSizePolicy(sizePolicy)
        self.info_block_title_value.setMinimumSize(QtCore.QSize(120, 20))
        self.info_block_title_value.setMaximumSize(QtCore.QSize(16777215, 45))
        self.info_block_title_value.setWordWrap(True)
        self.info_block_title_value.setObjectName("info_block_title_value")
        self.info_block_title.addWidget(self.info_block_title_value)
        self.verticalLayout_4.addLayout(self.info_block_title)
        self.info_block_serie = QtWidgets.QHBoxLayout()
        self.info_block_serie.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.info_block_serie.setSpacing(0)
        self.info_block_serie.setObjectName("info_block_serie")
        self.info_block_serie_label = QtWidgets.QLabel(self.info_block_contents)
        self.info_block_serie_label.setMinimumSize(QtCore.QSize(70, 20))
        self.info_block_serie_label.setMaximumSize(QtCore.QSize(70, 20))
        self.info_block_serie_label.setObjectName("info_block_serie_label")
        self.info_block_serie.addWidget(self.info_block_serie_label)
        self.info_block_serie_value = QtWidgets.QLabel(self.info_block_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_block_serie_value.sizePolicy().hasHeightForWidth())
        self.info_block_serie_value.setSizePolicy(sizePolicy)
        self.info_block_serie_value.setMinimumSize(QtCore.QSize(120, 20))
        self.info_block_serie_value.setMaximumSize(QtCore.QSize(16777215, 45))
        self.info_block_serie_value.setWordWrap(True)
        self.info_block_serie_value.setObjectName("info_block_serie_value")
        self.info_block_serie.addWidget(self.info_block_serie_value)
        self.verticalLayout_4.addLayout(self.info_block_serie)
        self.info_block_authors = QtWidgets.QHBoxLayout()
        self.info_block_authors.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.info_block_authors.setSpacing(0)
        self.info_block_authors.setObjectName("info_block_authors")
        self.info_block_authors_label = QtWidgets.QLabel(self.info_block_contents)
        self.info_block_authors_label.setMinimumSize(QtCore.QSize(70, 20))
        self.info_block_authors_label.setMaximumSize(QtCore.QSize(70, 20))
        self.info_block_authors_label.setObjectName("info_block_authors_label")
        self.info_block_authors.addWidget(self.info_block_authors_label)
        self.info_block_authors_value = QtWidgets.QLabel(self.info_block_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_block_authors_value.sizePolicy().hasHeightForWidth())
        self.info_block_authors_value.setSizePolicy(sizePolicy)
        self.info_block_authors_value.setMinimumSize(QtCore.QSize(120, 20))
        self.info_block_authors_value.setMaximumSize(QtCore.QSize(16777215, 45))
        self.info_block_authors_value.setWordWrap(True)
        self.info_block_authors_value.setObjectName("info_block_authors_value")
        self.info_block_authors.addWidget(self.info_block_authors_value)
        self.verticalLayout_4.addLayout(self.info_block_authors)
        self.info_block_file_formats = QtWidgets.QHBoxLayout()
        self.info_block_file_formats.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.info_block_file_formats.setSpacing(0)
        self.info_block_file_formats.setObjectName("info_block_file_formats")
        self.info_block_file_formats_label = QtWidgets.QLabel(self.info_block_contents)
        self.info_block_file_formats_label.setMinimumSize(QtCore.QSize(70, 20))
        self.info_block_file_formats_label.setMaximumSize(QtCore.QSize(70, 20))
        self.info_block_file_formats_label.setObjectName("info_block_file_formats_label")
        self.info_block_file_formats.addWidget(self.info_block_file_formats_label)
        self.info_block_file_formats_value = QtWidgets.QLabel(self.info_block_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_block_file_formats_value.sizePolicy().hasHeightForWidth())
        self.info_block_file_formats_value.setSizePolicy(sizePolicy)
        self.info_block_file_formats_value.setMinimumSize(QtCore.QSize(120, 20))
        self.info_block_file_formats_value.setMaximumSize(QtCore.QSize(16777215, 45))
        self.info_block_file_formats_value.setStyleSheet("")
        self.info_block_file_formats_value.setWordWrap(True)
        self.info_block_file_formats_value.setObjectName("info_block_file_formats_value")
        self.info_block_file_formats.addWidget(self.info_block_file_formats_value)
        self.verticalLayout_4.addLayout(self.info_block_file_formats)
        self.info_block_size = QtWidgets.QHBoxLayout()
        self.info_block_size.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.info_block_size.setSpacing(0)
        self.info_block_size.setObjectName("info_block_size")
        self.info_block_size_label = QtWidgets.QLabel(self.info_block_contents)
        self.info_block_size_label.setMinimumSize(QtCore.QSize(70, 20))
        self.info_block_size_label.setMaximumSize(QtCore.QSize(70, 20))
        self.info_block_size_label.setObjectName("info_block_size_label")
        self.info_block_size.addWidget(self.info_block_size_label)
        self.info_block_size_value = QtWidgets.QLabel(self.info_block_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_block_size_value.sizePolicy().hasHeightForWidth())
        self.info_block_size_value.setSizePolicy(sizePolicy)
        self.info_block_size_value.setMinimumSize(QtCore.QSize(120, 20))
        self.info_block_size_value.setMaximumSize(QtCore.QSize(16777215, 45))
        self.info_block_size_value.setStyleSheet("")
        self.info_block_size_value.setWordWrap(True)
        self.info_block_size_value.setObjectName("info_block_size_value")
        self.info_block_size.addWidget(self.info_block_size_value)
        self.verticalLayout_4.addLayout(self.info_block_size)
        self.info_block_synopsis = QtWidgets.QVBoxLayout()
        self.info_block_synopsis.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.info_block_synopsis.setSpacing(0)
        self.info_block_synopsis.setObjectName("info_block_synopsis")
        self.verticalLayout_4.addLayout(self.info_block_synopsis)
        self.info_block.setWidget(self.info_block_contents)
        home_window.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.info_block)

        self.retranslateUi(home_window)
        QtCore.QMetaObject.connectSlotsByName(home_window)

    def retranslateUi(self, home_window: QtWidgets.QMainWindow):
        _translate = QtCore.QCoreApplication.translate
        home_window.setWindowTitle(_translate("home_window", "HomeWindow"))
        self.central_block_table.setSortingEnabled(True)
        item = self.central_block_table.verticalHeaderItem(0)
        item.setText(_translate("home_window", "1"))
        item = self.central_block_table.verticalHeaderItem(1)
        item.setText(_translate("home_window", "2"))
        item = self.central_block_table.horizontalHeaderItem(0)
        item.setText(_translate("home_window", "Title"))
        item = self.central_block_table.horizontalHeaderItem(1)
        item.setText(_translate("home_window", "Author"))
        item = self.central_block_table.horizontalHeaderItem(2)
        item.setText(_translate("home_window", "Serie"))
        item = self.central_block_table.horizontalHeaderItem(3)
        item.setText(_translate("home_window", "Tags"))
        item = self.central_block_table.horizontalHeaderItem(4)
        item.setText(_translate("home_window", "Modified"))
        __sortingEnabled = self.central_block_table.isSortingEnabled()
        self.central_block_table.setSortingEnabled(False)
        item = self.central_block_table.item(0, 0)
        item.setText(_translate("home_window", "aa"))
        item = self.central_block_table.item(0, 1)
        item.setText(_translate("home_window", "bb"))
        item = self.central_block_table.item(1, 0)
        item.setText(_translate("home_window", "ccc"))
        item = self.central_block_table.item(1, 1)
        item.setText(_translate("home_window", "ddd"))
        self.central_block_table.setSortingEnabled(__sortingEnabled)
        self.header_block.setWindowTitle(_translate("home_window", "  Barre d\'outils"))
        self.sorting_block.setWindowTitle(_translate("home_window", "  Filtres"))
        self.sorting_block_search_label.setText(_translate("home_window", "TextLabel"))
        self.sorting_block_tree.setSortingEnabled(False)
        self.sorting_block_tree.headerItem().setText(0, _translate("home_window", "Groupes"))
        __sortingEnabled = self.sorting_block_tree.isSortingEnabled()
        self.sorting_block_tree.setSortingEnabled(False)
        self.sorting_block_tree.topLevelItem(0).setText(0, _translate("home_window", "Tout"))
        self.sorting_block_tree.topLevelItem(1).setText(0, _translate("home_window", "Series"))
        self.sorting_block_tree.topLevelItem(1).child(0).setText(0, _translate("home_window", "Harry Potter"))
        self.sorting_block_tree.topLevelItem(1).child(1).setText(0, _translate("home_window", "Gundam"))
        self.sorting_block_tree.topLevelItem(2).setText(0, _translate("home_window", "Auteurs"))
        self.sorting_block_tree.topLevelItem(2).child(0).setText(0, _translate("home_window", "truc"))
        self.sorting_block_tree.topLevelItem(2).child(1).setText(0, _translate("home_window", "machin"))
        self.sorting_block_tree.topLevelItem(3).setText(0, _translate("home_window", "Tags"))
        self.sorting_block_tree.topLevelItem(3).child(0).setText(0, _translate("home_window", "Huge"))
        self.sorting_block_tree.topLevelItem(3).child(1).setText(0, _translate("home_window", "Sword"))
        self.sorting_block_tree.topLevelItem(3).child(2).setText(0, _translate("home_window", "Depth"))
        self.sorting_block_tree.topLevelItem(3).child(3).setText(0, _translate("home_window", "Pit"))
        self.sorting_block_tree.setSortingEnabled(__sortingEnabled)
        self.info_block.setWindowTitle(_translate("home_window", "  Infos"))
        self.info_block_title_label.setText(_translate("home_window", "TextLabel"))
        self.info_block_title_value.setText(_translate("home_window", "TextLabel"))
        self.info_block_serie_label.setText(_translate("home_window", "TextLabel"))
        self.info_block_serie_value.setText(_translate("home_window", "TextLabel"))
        self.info_block_authors_label.setText(_translate("home_window", "TextLabel"))
        self.info_block_authors_value.setText(_translate("home_window", "TextLabel"))
        self.info_block_file_formats_label.setText(_translate("home_window", "TextLabel"))
        self.info_block_file_formats_value.setText(_translate("home_window", "<a href=\"test\">test</a>"))
        self.info_block_size_label.setText(_translate("home_window", "TextLabel"))
        self.info_block_size_value.setText(_translate("home_window", "TextLabel"))
from DockWidget import DockWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    home_window = QtWidgets.QMainWindow()
    ui = Ui_home_window()
    ui.setupUi(home_window)
    home_window.show()
    sys.exit(app.exec_())
