# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\CODES\Python\EbookCollection\settings.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog: QtWidgets.QDialog):
        dialog.setObjectName("dialog")
        dialog.resize(480, 450)
        dialog.setMinimumSize(QtCore.QSize(480, 450))
        dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        dialog.setAutoFillBackground(True)
        dialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(dialog)
        self.verticalLayout_2.setContentsMargins(1, 3, 3, 3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dialog_tabs = QtWidgets.QTabWidget(dialog)
        self.dialog_tabs.setMinimumSize(QtCore.QSize(50, 50))
        self.dialog_tabs.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dialog_tabs.setAutoFillBackground(False)
        self.dialog_tabs.setStyleSheet("")
        self.dialog_tabs.setTabPosition(QtWidgets.QTabWidget.West)
        self.dialog_tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.dialog_tabs.setIconSize(QtCore.QSize(50, 50))
        self.dialog_tabs.setElideMode(QtCore.Qt.ElideMiddle)
        self.dialog_tabs.setDocumentMode(True)
        self.dialog_tabs.setTabBarAutoHide(False)
        self.dialog_tabs.setObjectName("dialog_tabs")
        self.tab_global = QtWidgets.QWidget()
        self.tab_global.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab_global.setToolTip("")
        self.tab_global.setAutoFillBackground(True)
        self.tab_global.setStyleSheet("")
        self.tab_global.setObjectName("tab_global")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_global)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_global_scroll_area = QtWidgets.QScrollArea(self.tab_global)
        self.tab_global_scroll_area.setAutoFillBackground(False)
        self.tab_global_scroll_area.setStyleSheet("")
        self.tab_global_scroll_area.setWidgetResizable(True)
        self.tab_global_scroll_area.setObjectName("tab_global_scroll_area")
        self.tab_global_vl = QtWidgets.QWidget()
        self.tab_global_vl.setGeometry(QtCore.QRect(0, 0, 449, 415))
        self.tab_global_vl.setObjectName("tab_global_vl")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_global_vl)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tab_global_label = QtWidgets.QLabel(self.tab_global_vl)
        self.tab_global_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab_global_label.setObjectName("tab_global_label")
        self.verticalLayout_11.addWidget(self.tab_global_label)
        self.tab_global_lang_group_box = QtWidgets.QGroupBox(self.tab_global_vl)
        self.tab_global_lang_group_box.setMinimumSize(QtCore.QSize(0, 50))
        self.tab_global_lang_group_box.setObjectName("tab_global_lang_group_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_global_lang_group_box)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tab_global_lang_hl = QtWidgets.QHBoxLayout()
        self.tab_global_lang_hl.setObjectName("tab_global_lang_hl")
        self.tab_global_lang_combo_box = QtWidgets.QComboBox(self.tab_global_lang_group_box)
        self.tab_global_lang_combo_box.setObjectName("tab_global_lang_combo_box")
        self.tab_global_lang_combo_box.addItem("")
        self.tab_global_lang_combo_box.addItem("")
        self.tab_global_lang_combo_box.addItem("")
        self.tab_global_lang_hl.addWidget(self.tab_global_lang_combo_box)
        self.tab_global_lang_btn = QtWidgets.QPushButton(self.tab_global_lang_group_box)
        self.tab_global_lang_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab_global_lang_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tab_global_lang_btn.setObjectName("tab_global_lang_btn")
        self.tab_global_lang_hl.addWidget(self.tab_global_lang_btn)
        self.verticalLayout_3.addLayout(self.tab_global_lang_hl)
        self.verticalLayout_11.addWidget(self.tab_global_lang_group_box)
        self.tab_global_style_group_box = QtWidgets.QGroupBox(self.tab_global_vl)
        self.tab_global_style_group_box.setMinimumSize(QtCore.QSize(0, 50))
        self.tab_global_style_group_box.setObjectName("tab_global_style_group_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_global_style_group_box)
        self.verticalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tab_global_style_hl = QtWidgets.QHBoxLayout()
        self.tab_global_style_hl.setObjectName("tab_global_style_hl")
        self.tab_global_style_combo_box = QtWidgets.QComboBox(self.tab_global_style_group_box)
        self.tab_global_style_combo_box.setObjectName("tab_global_style_combo_box")
        self.tab_global_style_combo_box.addItem("")
        self.tab_global_style_combo_box.addItem("")
        self.tab_global_style_hl.addWidget(self.tab_global_style_combo_box)
        self.tab_global_style_import_btn = QtWidgets.QPushButton(self.tab_global_style_group_box)
        self.tab_global_style_import_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab_global_style_import_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tab_global_style_import_btn.setObjectName("tab_global_style_import_btn")
        self.tab_global_style_hl.addWidget(self.tab_global_style_import_btn)
        self.verticalLayout_4.addLayout(self.tab_global_style_hl)
        self.verticalLayout_11.addWidget(self.tab_global_style_group_box)
        self.tab_global_library_group_box = QtWidgets.QGroupBox(self.tab_global_vl)
        self.tab_global_library_group_box.setObjectName("tab_global_library_group_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_global_library_group_box)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tab_global_library_folder_label = QtWidgets.QLabel(self.tab_global_library_group_box)
        self.tab_global_library_folder_label.setObjectName("tab_global_library_folder_label")
        self.verticalLayout_5.addWidget(self.tab_global_library_folder_label)
        self.tab_global_library_hl1 = QtWidgets.QHBoxLayout()
        self.tab_global_library_hl1.setObjectName("tab_global_library_hl1")
        self.tab_global_library_folder_line_edit = QtWidgets.QLineEdit(self.tab_global_library_group_box)
        self.tab_global_library_folder_line_edit.setReadOnly(True)
        self.tab_global_library_folder_line_edit.setObjectName("tab_global_library_folder_line_edit")
        self.tab_global_library_hl1.addWidget(self.tab_global_library_folder_line_edit)
        self.tab_global_library_folder_btn = QtWidgets.QPushButton(self.tab_global_library_group_box)
        self.tab_global_library_folder_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab_global_library_folder_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tab_global_library_folder_btn.setObjectName("tab_global_library_folder_btn")
        self.tab_global_library_hl1.addWidget(self.tab_global_library_folder_btn)
        self.verticalLayout_5.addLayout(self.tab_global_library_hl1)
        self.verticalLayout_11.addWidget(self.tab_global_library_group_box)
        self.tab_global_archiver_group_box = QtWidgets.QGroupBox(self.tab_global_vl)
        self.tab_global_archiver_group_box.setObjectName("tab_global_archiver_group_box")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_global_archiver_group_box)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tab_global_archiver_folder_label = QtWidgets.QLabel(self.tab_global_archiver_group_box)
        self.tab_global_archiver_folder_label.setObjectName("tab_global_archiver_folder_label")
        self.verticalLayout_8.addWidget(self.tab_global_archiver_folder_label)
        self.tab_global_archiver_hl1 = QtWidgets.QHBoxLayout()
        self.tab_global_archiver_hl1.setObjectName("tab_global_archiver_hl1")
        self.tab_global_archiver_folder_line_edit = QtWidgets.QLineEdit(self.tab_global_archiver_group_box)
        self.tab_global_archiver_folder_line_edit.setReadOnly(True)
        self.tab_global_archiver_folder_line_edit.setObjectName("tab_global_archiver_folder_line_edit")
        self.tab_global_archiver_hl1.addWidget(self.tab_global_archiver_folder_line_edit)
        self.tab_global_archiver_folder_test_btn = QtWidgets.QPushButton(self.tab_global_archiver_group_box)
        self.tab_global_archiver_folder_test_btn.setObjectName("tab_global_archiver_folder_test_btn")
        self.tab_global_archiver_hl1.addWidget(self.tab_global_archiver_folder_test_btn)
        self.tab_global_archiver_folder_browse_btn = QtWidgets.QPushButton(self.tab_global_archiver_group_box)
        self.tab_global_archiver_folder_browse_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab_global_archiver_folder_browse_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tab_global_archiver_folder_browse_btn.setObjectName("tab_global_archiver_folder_browse_btn")
        self.tab_global_archiver_hl1.addWidget(self.tab_global_archiver_folder_browse_btn)
        self.verticalLayout_8.addLayout(self.tab_global_archiver_hl1)
        self.verticalLayout_11.addWidget(self.tab_global_archiver_group_box)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.tab_global_scroll_area.setWidget(self.tab_global_vl)
        self.verticalLayout.addWidget(self.tab_global_scroll_area)
        self.dialog_tabs.addTab(self.tab_global, "")
        self.tab_metadata = QtWidgets.QWidget()
        self.tab_metadata.setObjectName("tab_metadata")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_metadata)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tab_metadata_scroll_area = QtWidgets.QScrollArea(self.tab_metadata)
        self.tab_metadata_scroll_area.setWidgetResizable(True)
        self.tab_metadata_scroll_area.setObjectName("tab_metadata_scroll_area")
        self.tab_metadata_vl = QtWidgets.QWidget()
        self.tab_metadata_vl.setGeometry(QtCore.QRect(0, 0, 449, 415))
        self.tab_metadata_vl.setObjectName("tab_metadata_vl")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_metadata_vl)
        self.verticalLayout_12.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tab_metadata_default_cover_group_box = QtWidgets.QGroupBox(self.tab_metadata_vl)
        self.tab_metadata_default_cover_group_box.setMinimumSize(QtCore.QSize(0, 250))
        self.tab_metadata_default_cover_group_box.setFlat(False)
        self.tab_metadata_default_cover_group_box.setObjectName("tab_metadata_default_cover_group_box")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_metadata_default_cover_group_box)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab_metadata_default_cover_preview = QtWidgets.QPushButton(self.tab_metadata_default_cover_group_box)
        self.tab_metadata_default_cover_preview.setMinimumSize(QtCore.QSize(190, 160))
        self.tab_metadata_default_cover_preview.setMaximumSize(QtCore.QSize(190, 160))
        self.tab_metadata_default_cover_preview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tab_metadata_default_cover_preview.setStyleSheet("background: transparent !important;")
        self.tab_metadata_default_cover_preview.setText("")
        self.tab_metadata_default_cover_preview.setIconSize(QtCore.QSize(160, 160))
        self.tab_metadata_default_cover_preview.setFlat(False)
        self.tab_metadata_default_cover_preview.setObjectName("tab_metadata_default_cover_preview")
        self.horizontalLayout.addWidget(self.tab_metadata_default_cover_preview)
        self.tab_metadata_default_cover_vl = QtWidgets.QVBoxLayout()
        self.tab_metadata_default_cover_vl.setObjectName("tab_metadata_default_cover_vl")
        self.tab_metadata_default_cover_hl1 = QtWidgets.QHBoxLayout()
        self.tab_metadata_default_cover_hl1.setObjectName("tab_metadata_default_cover_hl1")
        self.tab_metadata_default_cover_background_label = QtWidgets.QLabel(self.tab_metadata_default_cover_group_box)
        self.tab_metadata_default_cover_background_label.setMinimumSize(QtCore.QSize(120, 0))
        self.tab_metadata_default_cover_background_label.setObjectName("tab_metadata_default_cover_background_label")
        self.tab_metadata_default_cover_hl1.addWidget(self.tab_metadata_default_cover_background_label)
        self.tab_metadata_default_cover_background_combo_box = QtWidgets.QComboBox(self.tab_metadata_default_cover_group_box)
        self.tab_metadata_default_cover_background_combo_box.setObjectName("tab_metadata_default_cover_background_combo_box")
        self.tab_metadata_default_cover_hl1.addWidget(self.tab_metadata_default_cover_background_combo_box)
        self.tab_metadata_default_cover_vl.addLayout(self.tab_metadata_default_cover_hl1)
        self.tab_metadata_default_cover_hl2 = QtWidgets.QHBoxLayout()
        self.tab_metadata_default_cover_hl2.setObjectName("tab_metadata_default_cover_hl2")
        self.tab_metadata_default_cover_pattern_label = QtWidgets.QLabel(self.tab_metadata_default_cover_group_box)
        self.tab_metadata_default_cover_pattern_label.setMinimumSize(QtCore.QSize(120, 0))
        self.tab_metadata_default_cover_pattern_label.setObjectName("tab_metadata_default_cover_pattern_label")
        self.tab_metadata_default_cover_hl2.addWidget(self.tab_metadata_default_cover_pattern_label)
        self.tab_metadata_default_cover_pattern_combo_box = QtWidgets.QComboBox(self.tab_metadata_default_cover_group_box)
        self.tab_metadata_default_cover_pattern_combo_box.setObjectName("tab_metadata_default_cover_pattern_combo_box")
        self.tab_metadata_default_cover_hl2.addWidget(self.tab_metadata_default_cover_pattern_combo_box)
        self.tab_metadata_default_cover_vl.addLayout(self.tab_metadata_default_cover_hl2)
        self.tab_metadata_default_cover_hl2_2 = QtWidgets.QHBoxLayout()
        self.tab_metadata_default_cover_hl2_2.setObjectName("tab_metadata_default_cover_hl2_2")
        self.tab_metadata_default_cover_pattern_color_label = QtWidgets.QLabel(self.tab_metadata_default_cover_group_box)
        self.tab_metadata_default_cover_pattern_color_label.setMinimumSize(QtCore.QSize(120, 0))
        self.tab_metadata_default_cover_pattern_color_label.setObjectName("tab_metadata_default_cover_pattern_color_label")
        self.tab_metadata_default_cover_hl2_2.addWidget(self.tab_metadata_default_cover_pattern_color_label)
        self.tab_metadata_default_cover_pattern_color_combo_box = QtWidgets.QComboBox(self.tab_metadata_default_cover_group_box)
        self.tab_metadata_default_cover_pattern_color_combo_box.setObjectName("tab_metadata_default_cover_pattern_color_combo_box")
        self.tab_metadata_default_cover_hl2_2.addWidget(self.tab_metadata_default_cover_pattern_color_combo_box)
        self.tab_metadata_default_cover_vl.addLayout(self.tab_metadata_default_cover_hl2_2)
        self.tab_metadata_default_cover_hl3 = QtWidgets.QHBoxLayout()
        self.tab_metadata_default_cover_hl3.setObjectName("tab_metadata_default_cover_hl3")
        self.tab_metadata_default_cover_title_label = QtWidgets.QLabel(self.tab_metadata_default_cover_group_box)
        self.tab_metadata_default_cover_title_label.setMinimumSize(QtCore.QSize(120, 0))
        self.tab_metadata_default_cover_title_label.setObjectName("tab_metadata_default_cover_title_label")
        self.tab_metadata_default_cover_hl3.addWidget(self.tab_metadata_default_cover_title_label)
        self.tab_metadata_default_cover_title_combo_box = QtWidgets.QComboBox(self.tab_metadata_default_cover_group_box)
        self.tab_metadata_default_cover_title_combo_box.setObjectName("tab_metadata_default_cover_title_combo_box")
        self.tab_metadata_default_cover_hl3.addWidget(self.tab_metadata_default_cover_title_combo_box)
        self.tab_metadata_default_cover_vl.addLayout(self.tab_metadata_default_cover_hl3)
        self.tab_metadata_default_cover_hl4 = QtWidgets.QHBoxLayout()
        self.tab_metadata_default_cover_hl4.setObjectName("tab_metadata_default_cover_hl4")
        self.tab_metadata_default_cover_series_label = QtWidgets.QLabel(self.tab_metadata_default_cover_group_box)
        self.tab_metadata_default_cover_series_label.setMinimumSize(QtCore.QSize(120, 0))
        self.tab_metadata_default_cover_series_label.setObjectName("tab_metadata_default_cover_series_label")
        self.tab_metadata_default_cover_hl4.addWidget(self.tab_metadata_default_cover_series_label)
        self.tab_metadata_default_cover_series_combo_box = QtWidgets.QComboBox(self.tab_metadata_default_cover_group_box)
        self.tab_metadata_default_cover_series_combo_box.setObjectName("tab_metadata_default_cover_series_combo_box")
        self.tab_metadata_default_cover_hl4.addWidget(self.tab_metadata_default_cover_series_combo_box)
        self.tab_metadata_default_cover_vl.addLayout(self.tab_metadata_default_cover_hl4)
        self.tab_metadata_default_cover_hl5 = QtWidgets.QHBoxLayout()
        self.tab_metadata_default_cover_hl5.setObjectName("tab_metadata_default_cover_hl5")
        self.tab_metadata_default_cover_authors_label = QtWidgets.QLabel(self.tab_metadata_default_cover_group_box)
        self.tab_metadata_default_cover_authors_label.setMinimumSize(QtCore.QSize(120, 0))
        self.tab_metadata_default_cover_authors_label.setObjectName("tab_metadata_default_cover_authors_label")
        self.tab_metadata_default_cover_hl5.addWidget(self.tab_metadata_default_cover_authors_label)
        self.tab_metadata_default_cover_authors_combo_box = QtWidgets.QComboBox(self.tab_metadata_default_cover_group_box)
        self.tab_metadata_default_cover_authors_combo_box.setObjectName("tab_metadata_default_cover_authors_combo_box")
        self.tab_metadata_default_cover_hl5.addWidget(self.tab_metadata_default_cover_authors_combo_box)
        self.tab_metadata_default_cover_vl.addLayout(self.tab_metadata_default_cover_hl5)
        self.horizontalLayout.addLayout(self.tab_metadata_default_cover_vl)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_12.addWidget(self.tab_metadata_default_cover_group_box)
        self.tab_metadata_import_group_box = QtWidgets.QGroupBox(self.tab_metadata_vl)
        self.tab_metadata_import_group_box.setMinimumSize(QtCore.QSize(0, 130))
        self.tab_metadata_import_group_box.setStyleSheet("gridline-color: rgb(255, 0, 127);")
        self.tab_metadata_import_group_box.setFlat(False)
        self.tab_metadata_import_group_box.setObjectName("tab_metadata_import_group_box")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_metadata_import_group_box)
        self.verticalLayout_10.setContentsMargins(-1, 0, -1, 9)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tab_metadata_import_filename_template_label = QtWidgets.QLabel(self.tab_metadata_import_group_box)
        self.tab_metadata_import_filename_template_label.setAutoFillBackground(True)
        self.tab_metadata_import_filename_template_label.setObjectName("tab_metadata_import_filename_template_label")
        self.verticalLayout_10.addWidget(self.tab_metadata_import_filename_template_label)
        self.tab_metadata_import_filename_template_combo_box = QtWidgets.QComboBox(self.tab_metadata_import_group_box)
        self.tab_metadata_import_filename_template_combo_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab_metadata_import_filename_template_combo_box.setObjectName("tab_metadata_import_filename_template_combo_box")
        self.verticalLayout_10.addWidget(self.tab_metadata_import_filename_template_combo_box)
        self.tab_metadata_import_hl2 = QtWidgets.QHBoxLayout()
        self.tab_metadata_import_hl2.setObjectName("tab_metadata_import_hl2")
        self.tab_metadata_import_filename_separator_label = QtWidgets.QLabel(self.tab_metadata_import_group_box)
        self.tab_metadata_import_filename_separator_label.setAutoFillBackground(True)
        self.tab_metadata_import_filename_separator_label.setObjectName("tab_metadata_import_filename_separator_label")
        self.tab_metadata_import_hl2.addWidget(self.tab_metadata_import_filename_separator_label)
        self.tab_metadata_import_filename_separator_line_edit = QtWidgets.QLineEdit(self.tab_metadata_import_group_box)
        self.tab_metadata_import_filename_separator_line_edit.setAutoFillBackground(False)
        self.tab_metadata_import_filename_separator_line_edit.setObjectName("tab_metadata_import_filename_separator_line_edit")
        self.tab_metadata_import_hl2.addWidget(self.tab_metadata_import_filename_separator_line_edit)
        self.verticalLayout_10.addLayout(self.tab_metadata_import_hl2)
        self.verticalLayout_12.addWidget(self.tab_metadata_import_group_box)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem2)
        self.tab_metadata_scroll_area.setWidget(self.tab_metadata_vl)
        self.verticalLayout_7.addWidget(self.tab_metadata_scroll_area)
        self.dialog_tabs.addTab(self.tab_metadata, "")
        self.tab_sync = QtWidgets.QWidget()
        self.tab_sync.setObjectName("tab_sync")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_sync)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.tab_sync_interface_group = QtWidgets.QGroupBox(self.tab_sync)
        self.tab_sync_interface_group.setObjectName("tab_sync_interface_group")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_sync_interface_group)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.tab_sync_interface_layout = QtWidgets.QFormLayout()
        self.tab_sync_interface_layout.setObjectName("tab_sync_interface_layout")
        self.tab_sync_interface_ip_label = QtWidgets.QLabel(self.tab_sync_interface_group)
        self.tab_sync_interface_ip_label.setObjectName("tab_sync_interface_ip_label")
        self.tab_sync_interface_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tab_sync_interface_ip_label)
        self.tab_sync_interface_ip_edit = QtWidgets.QLineEdit(self.tab_sync_interface_group)
        self.tab_sync_interface_ip_edit.setClearButtonEnabled(False)
        self.tab_sync_interface_ip_edit.setObjectName("tab_sync_interface_ip_edit")
        self.tab_sync_interface_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tab_sync_interface_ip_edit)
        self.tab_sync_interface_port_label = QtWidgets.QLabel(self.tab_sync_interface_group)
        self.tab_sync_interface_port_label.setObjectName("tab_sync_interface_port_label")
        self.tab_sync_interface_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tab_sync_interface_port_label)
        self.tab_sync_interface_port_edit = QtWidgets.QLineEdit(self.tab_sync_interface_group)
        self.tab_sync_interface_port_edit.setObjectName("tab_sync_interface_port_edit")
        self.tab_sync_interface_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tab_sync_interface_port_edit)
        self.verticalLayout_15.addLayout(self.tab_sync_interface_layout)
        self.verticalLayout_14.addWidget(self.tab_sync_interface_group)
        self.tab_sync_identification = QtWidgets.QGroupBox(self.tab_sync)
        self.tab_sync_identification.setObjectName("tab_sync_identification")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_sync_identification)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.tab_sync_identification_layout = QtWidgets.QFormLayout()
        self.tab_sync_identification_layout.setObjectName("tab_sync_identification_layout")
        self.tab_sync_identification_user_label = QtWidgets.QLabel(self.tab_sync_identification)
        self.tab_sync_identification_user_label.setObjectName("tab_sync_identification_user_label")
        self.tab_sync_identification_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tab_sync_identification_user_label)
        self.tab_sync_identification_user_edit = QtWidgets.QLineEdit(self.tab_sync_identification)
        self.tab_sync_identification_user_edit.setClearButtonEnabled(True)
        self.tab_sync_identification_user_edit.setObjectName("tab_sync_identification_user_edit")
        self.tab_sync_identification_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tab_sync_identification_user_edit)
        self.tab_sync_identification_password_label = QtWidgets.QLabel(self.tab_sync_identification)
        self.tab_sync_identification_password_label.setObjectName("tab_sync_identification_password_label")
        self.tab_sync_identification_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tab_sync_identification_password_label)
        self.tab_sync_identification_password_edit = QtWidgets.QLineEdit(self.tab_sync_identification)
        self.tab_sync_identification_password_edit.setClearButtonEnabled(True)
        self.tab_sync_identification_password_edit.setObjectName("tab_sync_identification_password_edit")
        self.tab_sync_identification_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tab_sync_identification_password_edit)
        self.verticalLayout_17.addLayout(self.tab_sync_identification_layout)
        self.verticalLayout_14.addWidget(self.tab_sync_identification)
        self.tab_sync_warn_layout = QtWidgets.QFormLayout()
        self.tab_sync_warn_layout.setObjectName("tab_sync_warn_layout")
        self.tab_sync_warn_icon = QtWidgets.QLabel(self.tab_sync)
        self.tab_sync_warn_icon.setMaximumSize(QtCore.QSize(30, 30))
        self.tab_sync_warn_icon.setAutoFillBackground(False)
        self.tab_sync_warn_icon.setText("")
        self.tab_sync_warn_icon.setPixmap(QtGui.QPixmap("ressources/icons/tmp/dialog_warning.png"))
        self.tab_sync_warn_icon.setScaledContents(True)
        self.tab_sync_warn_icon.setObjectName("tab_sync_warn_icon")
        self.tab_sync_warn_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tab_sync_warn_icon)
        self.tab_sync_warn_text = QtWidgets.QLabel(self.tab_sync)
        self.tab_sync_warn_text.setObjectName("tab_sync_warn_text")
        self.tab_sync_warn_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tab_sync_warn_text)
        self.verticalLayout_14.addLayout(self.tab_sync_warn_layout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem3)
        self.dialog_tabs.addTab(self.tab_sync, "")
        self.tab_plugins = QtWidgets.QWidget()
        self.tab_plugins.setObjectName("tab_plugins")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_plugins)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.tab_plugins_scroll_area1 = QtWidgets.QScrollArea(self.tab_plugins)
        self.tab_plugins_scroll_area1.setWidgetResizable(True)
        self.tab_plugins_scroll_area1.setObjectName("tab_plugins_scroll_area1")
        self.tab_plugins_scroll_area1_content = QtWidgets.QWidget()
        self.tab_plugins_scroll_area1_content.setGeometry(QtCore.QRect(0, 0, 449, 415))
        self.tab_plugins_scroll_area1_content.setObjectName("tab_plugins_scroll_area1_content")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_plugins_scroll_area1_content)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab_plugins_scroll_area1_content)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.tab_plugins_import = QtWidgets.QPushButton(self.tab_plugins_scroll_area1_content)
        self.tab_plugins_import.setObjectName("tab_plugins_import")
        self.horizontalLayout_3.addWidget(self.tab_plugins_import)
        self.verticalLayout_16.addLayout(self.horizontalLayout_3)
        self.tab_plugins_list_zone = QtWidgets.QVBoxLayout()
        self.tab_plugins_list_zone.setObjectName("tab_plugins_list_zone")
        self.verticalLayout_16.addLayout(self.tab_plugins_list_zone)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem4)
        self.tab_plugins_scroll_area1.setWidget(self.tab_plugins_scroll_area1_content)
        self.verticalLayout_13.addWidget(self.tab_plugins_scroll_area1)
        self.dialog_tabs.addTab(self.tab_plugins, "")
        self.tab_about = QtWidgets.QWidget()
        self.tab_about.setObjectName("tab_about")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_about)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tab_about_scroll_area = QtWidgets.QScrollArea(self.tab_about)
        self.tab_about_scroll_area.setWidgetResizable(True)
        self.tab_about_scroll_area.setObjectName("tab_about_scroll_area")
        self.tab_about_vl = QtWidgets.QWidget()
        self.tab_about_vl.setGeometry(QtCore.QRect(0, 0, 431, 397))
        self.tab_about_vl.setObjectName("tab_about_vl")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_about_vl)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tab_about_label = QtWidgets.QLabel(self.tab_about_vl)
        self.tab_about_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.tab_about_label.setWordWrap(True)
        self.tab_about_label.setObjectName("tab_about_label")
        self.verticalLayout_9.addWidget(self.tab_about_label)
        self.tab_about_hl = QtWidgets.QHBoxLayout()
        self.tab_about_hl.setObjectName("tab_about_hl")
        self.tab_about_btn_license = QtWidgets.QPushButton(self.tab_about_vl)
        self.tab_about_btn_license.setObjectName("tab_about_btn_license")
        self.tab_about_hl.addWidget(self.tab_about_btn_license)
        self.tab_about_btn_website = QtWidgets.QPushButton(self.tab_about_vl)
        self.tab_about_btn_website.setObjectName("tab_about_btn_website")
        self.tab_about_hl.addWidget(self.tab_about_btn_website)
        self.verticalLayout_9.addLayout(self.tab_about_hl)
        self.tab_about_scroll_area.setWidget(self.tab_about_vl)
        self.verticalLayout_6.addWidget(self.tab_about_scroll_area)
        self.dialog_tabs.addTab(self.tab_about, "")
        self.verticalLayout_2.addWidget(self.dialog_tabs)
        self.button_box = QtWidgets.QDialogButtonBox(dialog)
        self.button_box.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout_2.addWidget(self.button_box)

        self.retranslateUi(dialog)
        self.dialog_tabs.setCurrentIndex(2)
        self.button_box.accepted.connect(dialog.accept)
        self.button_box.rejected.connect(dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog: QtWidgets.QDialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Dialog"))
        self.tab_global_label.setText(_translate("dialog", "TextLabel"))
        self.tab_global_lang_group_box.setTitle(_translate("dialog", "Language"))
        self.tab_global_lang_combo_box.setItemText(0, _translate("dialog", "<Automatic>"))
        self.tab_global_lang_combo_box.setItemText(1, _translate("dialog", "English"))
        self.tab_global_lang_combo_box.setItemText(2, _translate("dialog", "Français"))
        self.tab_global_lang_btn.setText(_translate("dialog", "Import"))
        self.tab_global_style_group_box.setTitle(_translate("dialog", "Style"))
        self.tab_global_style_combo_box.setItemText(0, _translate("dialog", "Dark"))
        self.tab_global_style_combo_box.setItemText(1, _translate("dialog", "Light"))
        self.tab_global_style_import_btn.setText(_translate("dialog", "Import"))
        self.tab_global_library_group_box.setTitle(_translate("dialog", "Library"))
        self.tab_global_library_folder_label.setText(_translate("dialog", "Storagefolder"))
        self.tab_global_library_folder_btn.setText(_translate("dialog", "Parcourir..."))
        self.tab_global_archiver_group_box.setTitle(_translate("dialog", "7zip"))
        self.tab_global_archiver_folder_label.setText(_translate("dialog", "Path"))
        self.tab_global_archiver_folder_test_btn.setText(_translate("dialog", "PushButton"))
        self.tab_global_archiver_folder_browse_btn.setText(_translate("dialog", "Parcourir..."))
        self.dialog_tabs.setTabText(self.dialog_tabs.indexOf(self.tab_global), _translate("dialog", "Global"))
        self.tab_metadata_default_cover_group_box.setTitle(_translate("dialog", "Default Cover Style"))
        self.tab_metadata_default_cover_background_label.setText(_translate("dialog", "Background"))
        self.tab_metadata_default_cover_pattern_label.setText(_translate("dialog", "Pattern"))
        self.tab_metadata_default_cover_pattern_color_label.setText(_translate("dialog", "Pattern Color"))
        self.tab_metadata_default_cover_title_label.setText(_translate("dialog", "Title"))
        self.tab_metadata_default_cover_series_label.setText(_translate("dialog", "Series"))
        self.tab_metadata_default_cover_authors_label.setText(_translate("dialog", "Authors"))
        self.tab_metadata_import_group_box.setTitle(_translate("dialog", "Import"))
        self.tab_metadata_import_filename_template_label.setText(_translate("dialog", "File name parse template"))
        self.tab_metadata_import_filename_separator_label.setText(_translate("dialog", "File name parse separator"))
        self.dialog_tabs.setTabText(self.dialog_tabs.indexOf(self.tab_metadata), _translate("dialog", "Metadata"))
        self.tab_sync_interface_group.setTitle(_translate("dialog", "Listening interface"))
        self.tab_sync_interface_ip_label.setText(_translate("dialog", "IP"))
        self.tab_sync_interface_port_label.setText(_translate("dialog", "Port"))
        self.tab_sync_identification.setTitle(_translate("dialog", "Identification"))
        self.tab_sync_identification_user_label.setText(_translate("dialog", "User"))
        self.tab_sync_identification_password_label.setText(_translate("dialog", "Password"))
        self.tab_sync_warn_text.setText(_translate("dialog", "Any changes in this panel need app restart"))
        self.dialog_tabs.setTabText(self.dialog_tabs.indexOf(self.tab_sync), _translate("dialog", "Sync"))
        self.label_2.setText(_translate("dialog", "Plugins"))
        self.tab_plugins_import.setText(_translate("dialog", "Import"))
        self.dialog_tabs.setTabText(self.dialog_tabs.indexOf(self.tab_plugins), _translate("dialog", "Plugins"))
        self.tab_about_label.setText(_translate("dialog", "EbookCollection\n"
"\n"
"MIT License\n"
"\n"
"Copyright (c) 2020-2021 Boulain Kévin"))
        self.tab_about_btn_license.setText(_translate("dialog", "License"))
        self.tab_about_btn_website.setText(_translate("dialog", "Web Site"))
        self.dialog_tabs.setTabText(self.dialog_tabs.indexOf(self.tab_about), _translate("dialog", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())
