# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\CODES\Python\EbookCollection\reader\reader.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReaderWindow(object):
    def setupUi(self, ReaderWindow):
        ReaderWindow.setObjectName("ReaderWindow")
        ReaderWindow.resize(600, 600)
        ReaderWindow.setMinimumSize(QtCore.QSize(600, 600))
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(ReaderWindow)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(ReaderWindow)
        self.treeWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.header().setVisible(False)
        self.verticalLayout.addWidget(self.treeWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(ReaderWindow)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(ReaderWindow)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.webView = QtWebKitWidgets.QWebView(ReaderWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setMinimumSize(QtCore.QSize(400, 720))
        self.webView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.webView.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.webView.setProperty("url", QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.horizontalLayout_6.addWidget(self.webView)

        self.retranslateUi(ReaderWindow)
        QtCore.QMetaObject.connectSlotsByName(ReaderWindow)

    def retranslateUi(self, ReaderWindow):
        _translate = QtCore.QCoreApplication.translate
        ReaderWindow.setWindowTitle(_translate("ReaderWindow", "Ebook Collection - Reader"))
        self.treeWidget.headerItem().setText(0, _translate("ReaderWindow", "1"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("ReaderWindow", "Cover"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("ReaderWindow", "Index"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("ReaderWindow", "Chapter 1"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("ReaderWindow", "Chapter 2"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("ReaderWindow", "PushButton"))
        self.pushButton.setText(_translate("ReaderWindow", "PushButton"))
from PyQt5 import QtWebKitWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReaderWindow = QtWidgets.QWidget()
    ui = Ui_ReaderWindow()
    ui.setupUi(ReaderWindow)
    ReaderWindow.show()
    sys.exit(app.exec_())
