; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#include "./Installer-common.iss"

[Setup]
OutputBaseFilename=setup_{#MyAppVersion}_full

[Files]  
Source: ".\python\*"; DestDir: "{app}\python"; Flags: ignoreversion  
Source: "test.bat"; DestDir: "{app}"

[Run]
Filename: "{app}\test.bat"; StatusMsg: "check and install dependencies"; Parameters: ""; Flags: shellexec