; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#include "./Installer-common.iss"

[Setup]
OutputBaseFilename=setup_{#MyAppVersion}_light